/* Autogenerated by pngtolights.py */

#include <Arduino.h>
#include <avr/pgmspace.h>
#define RGAM_DATA_COLUMNS 355
#define RGAM_DATA_ROWS 200
#define RGAM_COLORS 3
extern const byte data[RGAM_DATA_COLUMNS][RGAM_DATA_ROWS][RGAM_COLORS] PROGMEM;
